export const topDealUsers = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
      username: "Elva McDonald",
      firstName: "Elva",
      lastName: "McDonald",
      email: "elva@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'ADMIN',
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Linnie Nelson",
      firstName: "Linnie",
      lastName: "Nelson",
      email: "linnie@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Brent Reeves",
      firstName: "Brent",
      lastName: "Reeves",
      email: "brent@gmail.com",
      createdAt:"25th November 2023",
      role: 'ADMIN',
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Adeline Watson",
      firstName: "Adeline",
      lastName: "Watson",
      email: "adeline@gmail.com",
      createdAt:"25th November 2023",
      role: 'USER',
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Juan Harrington",
      firstName: "Juan",
      lastName: "Harrington",
      email: "juan@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Augusta McGee",
      firstName: "Augusta",
      lastName: "McGee",
      email: "augusta@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Augusta McGee",
      firstName: "Augusta",
      lastName: "McGee",
      email: "augusta@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Angel Thomas",
      firstName: "Angel",
      lastName: "Thomas",
      email: "angel@gmail.com",
      createdAt:"25th November 2023",
      role: 'USER',
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Angel Thomas",
      firstName: "Angel",
      lastName: "Thomas",
      email: "angel@gmail.com",
      createdAt:"25th November 2023",
      role: 'USER',
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Augusta McGee",
      firstName: "Augusta",
      lastName: "McGee",
      email: "augusta@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Brent Reeves",
      firstName: "Brent",
      lastName: "Reeves",
      email: "brent@gmail.com",
      createdAt:"25th November 2023",
      role: 'ADMIN',
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Adeline Watson",
      firstName: "Adeline",
      lastName: "Watson",
      email: "adeline@gmail.com",
      createdAt:"25th November 2023",
      role: 'USER',
    },
    {
      id: 13,
      img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Juan Harrington",
      firstName: "Juan",
      lastName: "Harrington",
      email: "juan@gmail.com",
      createdAt:"25th November 2023",
      verified: true,
      role: 'USER',
    },
  ];